import { appendFileSync, existsSync, readFileSync, writeFileSync } from "fs";

import { execCommand } from "../utils/config";

import type { DoctorIssue } from "../utils/types";

export function tryAutoFix(issue: DoctorIssue): boolean {
  if (!issue.autoFixable) return false;

  switch (issue.category) {
    case "env":
      return fixEnvVar(issue);
    case "prisma":
      return fixPrisma(issue);
    case "eslint":
      return fixESLint();
    case "pwa":
      return fixPWA();
    case "nextauth":
      return fixNextAuth(issue);
    default:
      return false;
  }
}

function fixEnvVar(issue: DoctorIssue): boolean {
  if (!issue.message.includes("未设置")) return false;

  const envKey = issue.message.split(" ")[0];
  const envFile = `${process.cwd()}/.env.local`;

  if (!existsSync(envFile)) {
    writeFileSync(envFile, `# Auto-generated by Project Doctor\n${envKey}=""\n`);
    return true;
  }

  const content = readFileSync(envFile, "utf-8");
  if (!content.includes(`${envKey}=`)) {
    appendFileSync(envFile, `\n${envKey}=""\n`);
    return true;
  }

  return false;
}

function fixNextAuth(issue: DoctorIssue): boolean {
  if (issue.message.includes("AUTH_URL")) {
    const envFile = `${process.cwd()}/.env.local`;
    if (existsSync(envFile)) {
      const content = readFileSync(envFile, "utf-8");
      if (!content.includes("AUTH_URL=")) {
        appendFileSync(envFile, '\nAUTH_URL="http://localhost:3000"\n');
        return true;
      }
    }
  }
  return false;
}

function fixPrisma(_issue: DoctorIssue): boolean {
  const { error } = execCommand("npx prisma generate");
  return !error || error.includes("Generated");
}

function fixESLint(): boolean {
  const { error } = execCommand("npx eslint . --fix");
  return !error || error.includes("0 errors") || error.includes("0 problems");
}

function fixPWA(): boolean {
  const { error } = execCommand("npm install next-pwa");
  return !error;
}
